# Scheduler jobs
# '0 * * * * *'   Runs every minute
# '0 */5 * * * *' Runs when second = 0, every 5 minutes
# '0 0 * * *' Runs at midnight

:schedule:
  vehicle_cities_elderships_scheduler_worker:
    cron: '0 */2 * * * *'
    class: VehicleCitiesEldershipsSchedulerWorker
    enabled: true
  vehicle_city_scheduler_worker:
    cron: '0 * * * * *'
    class: VehicleCitySchedulerWorker
    enabled: true
  vehicle_total_km_scheduler_worker:
    cron: '0 */5 * * * *'
    class: VehicleTotalKmSchedulerWorker
    enabled: true
  order_scheduler_worker:
    cron: '0 0 * * *'
    class: OrderSchedulerWorker
    enabled: true
