# Scheduler jobs
# '0 * * * * *'   Runs every minute
# '0 */5 * * * *' Runs when second = 0, every 5 minutes
# '0 0 * * *' Runs at midnight

:schedule:
  vehicle_scheduler_worker:
    cron: '0 */5 * * * *'
    class: VehicleSchedulerWorker
    enabled: true
  order_scheduler_worker:
    cron: '0 0 * * *'
    class: OrderSchedulerWorker
    enabled: true
